### ISSUE TITLE
User can view a list of engines 

### ISSUE THREAD

**Issue by Johnny-Baltazar** [Johnny-Baltazar/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of engines 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create an application that lists a variety of engine types that users can select to view their information. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue-1-screenshot](https://user-images.githubusercontent.com/25161542/153724335-98778c12-38f4-48cf-a765-50564ce2475f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header.
  - [x] Add background-color of blue to the header.
  - [x] Include a navigation  `<a>` tag for engines, that show the list of engines when clicked.  
- [x] Add a `<h1>` heading to the page.
- [x] Create a HMTL container with columns and rows for each engine application.
- [x] Add example engine images with headings.
- [x] Add eventListeners for clicks to the pictures and headings.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Add styling for mobile screen sizes.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
