### ISSUE TITLE
User can view each engine application.

### ISSUE THREAD

**Issue by Johnny-Baltazar** [Johnny-Baltazar/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view each engine page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Display each engine application with user entries, when the engine is selected/clicked. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-12 131416](https://user-images.githubusercontent.com/25161542/153728664-c8851d0e-5ebb-4951-afbb-d3beb7e68436.png)
![b18c1-view](https://user-images.githubusercontent.com/25161542/153728671-eef4efba-68a4-4e9b-b732-06f412ae71bd.png)
![b16a2-view](https://user-images.githubusercontent.com/25161542/153728673-5503e6ec-ec88-4c66-b579-a04f9b18c852.png)
![ls3-view](https://user-images.githubusercontent.com/25161542/153728678-290d74d2-b330-4721-8ffc-8a10f09b6c4d.png)
![mobile-figma](https://user-images.githubusercontent.com/25161542/163088729-f6dbb72c-e2c6-44bd-8471-71275c6271dc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a HMTL container with columns and rows for each engine application.
- [x] Add an engine image to each page.
- [x] Add text for a description of each engine.
- [x] Add a heading for each engine.
- [x] Add a sibling `div[data-view="entries"]` element in the HTML.
- [x] Add an empty unordered list to the `div[data-view="entries"]` elements in the HTML.
- [x] Add some dummy entries to the unordered list in the HTML and style them to match the wireframe.
- [x] Add some media queries, so that the pages look aligned in different screen sizes.
- [x] Check that the entries list looks good on both mobile and desktop screens for each engine application.
- [x] Create functionality that allows an engine page to be viewed when clicked from the home page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
