### ISSUE TITLE
User can decode their vehicle identification number. 

### ISSUE THREAD

**Issue by Johnny-Baltazar** [Johnny-Baltazar/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can decode their vehicle information number. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create search box that a user can search their vehicle information number. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-12 115306](https://user-images.githubusercontent.com/25161542/153726330-9f332361-334f-4fce-84e0-8794e3ea273c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an eventListener to the search `<button>`.
- [x] Make sure that 17 digits are required to be entered into the `<input>`.
- [x] Make sure the VIN is alphanumeric only.
- [x] Show a modal when the VIN is not 17 digits or not alphanumeric.
- [x] Close the modal if close is selected.
- [x] Ensure that a VIN can be decoded thru the NHTSA API.
- [x] Create a vehicle information page that opens when a vehicle identification number is searched. 
- [x] Add an exit button that exits the VIN decode page.
- [x] Make sure the VIN decode pages look good in mobile.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
