### ISSUE TITLE
User can add an entry of engine information and a picture to an engine category.

### ISSUE THREAD

**Issue by Johnny-Baltazar** [Johnny-Baltazar/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add an entry of engine information and a picture to an engine category.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users to store an image on an engine application page, that is related to the engine, and add some notes about the image.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-12 121147](https://user-images.githubusercontent.com/25161542/153726841-14938f36-d714-4624-abc7-f48712c09df0.png)

![user-can-add-entry](https://user-images.githubusercontent.com/25161542/153728117-355c304e-6198-418b-9737-d2884a43b533.png)

![subaru-page-screenshot](https://user-images.githubusercontent.com/25161542/153726857-5699851f-a8d8-436a-af50-82e8f3a55e06.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add event listeners to the plus buttons to open the entry form.
- [x] Add a `div[data-view="entry-form"]` to the HTML.
- [x] Add a form for creating an entry to the `div[data-view="entry-form"]`.
- [x] Ensure that the form looks nice in both mobile and desktop sized screens.
- [x] Make all inputs of the form required.
- [x] Listen for input events on the photoUrl input to update the `srcattribute' of the photo preview when the input value changes.
- [x] Define a function that takes a single `entry` object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Create a function that saves the entries to the local storage.
- [x] Use a loop to create a DOM tree for each entry in the data model and append it to the correct page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Ensure that submitting a new entry also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new entry automatically shows the posted entries without reloading the page.
- [x] Update the homepage link to include the `data-view` `entry-form`.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Test the app some more in a private browsing tab.
- [x] Listen for `'submit'` events on the entry form and:
  - [x] Put the form's input values into a new object.
  - [x] Add the `nextEntryId` to the object.
  - [x] Increment the `nextEntryId` on the data model.
  - [x] Prepend the new object to the entries in the data model.
  - [x] Reset the image preview's `src' attribute.
  - [x] Reset the form inputs.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new entry receives an incrementing `entryId`.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
