### ISSUE TITLE
User can edit an existing database entry.

### ISSUE THREAD

**Issue by Johnny-Baltazar** [Johnny-Baltazar/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit an existing database entry.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow users to select an entry to edit and pre-populate its information in the form. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot 2022-02-12 131416](https://user-images.githubusercontent.com/25161542/153728890-429e6c71-da87-4511-b0f4-10afa4cce1c1.png)

![Screenshot 2022-02-12 123816](https://user-images.githubusercontent.com/25161542/153727593-07a36afd-c7d9-439a-a709-9b0a6640694b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update entry rendering function to include an edit icon for each rendered entry.
- [x] Ensure that each rendered entry is given a `data-entry-id` attribute indicating which entry it is.
- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show the entry form if an edit icon was clicked.
- [x] Find the matching entry object in the data model and assign it to the data model's `editing` property if an edit icon was clicked.
- [x] Update the entry form's submit handler function to conditionally add a new entry object or update the existing one.
- [x] Update the entry form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] Pre-populate the entry form with the clicked entry's values from the object found in the data model.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
