### ISSUE TITLE
User can delete a database entry.

### ISSUE THREAD

**Issue by Johnny-Baltazar** [Johnny-Baltazar/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a database entry.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow users to delete an entry from its edit screen.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-12 124101](https://user-images.githubusercontent.com/25161542/153727665-0d71067f-9924-4531-aa7c-27762a4ccaa9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a click target for deleting an entry to the entry form that only appears if the user is editing an entry.
- [ ] Show a confirmation modal when the user clicks the Delete Entry click target.
- [ ] Hide the modal if the user clicks Cancel.
- [ ] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [ ] Show the current engine application if the user clicks Delete.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
